model:
  base_learning_rate: 3e-5
  target: ldm_autoencoder.ldm_autoencoder_v1.AutoEncLDM
  params:
    kl_loss_weight: 0.000001
    sd_lock_input: False
    sd_lock_middle: False
    sd_lock_output: False
    optimize_params_key: ~
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    cond_stage_key: "txt"
    frame_index_key: "frame_index"
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: train/loss_simple_epoch
    scale_factor: 0.18215
    use_ema: False
    learn_logvar: False
    validation_log_start_epoch: 0
    validation_log_every_epochs: 1

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1000 ] # NOTE for resuming. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    allow_gan: True
    gan_config:
      decode_z_to_frames: True
      generator_frequency: 1
      discriminator_frequency: 2
      adversarial_loss: hinge
      generator_loss_weight: 0.1
      discriminator:
        target: ldm_autoencoder.ldm_autoencoder_v1.FrameDiscriminator
        params:
          dims: 3
          image_size: 256
          in_channels: 3
          model_channels: 64
          num_res_blocks: 1
          spatial_attention_resolutions: [ 16, 32 ]
          temporal_attention_resolutions: [ 2, 4, 8, 16, 32 ]
          channel_mult: [ 1, 2, 3, 4, 4 ] # [128, 64, 32, 16, -]
          num_head_channels: 32
          use_checkpoint: True
          legacy: False
          temporal_embeddings: True

    videocontent_key: "full_frame"
    videoenc_config:
      target: ldm_autoencoder.ldm_autoencoder_v1.VideoContentEnc
      params:
        dims: 3
        image_size: 32
        in_channels: 4
        out_channels: 16 # vc shape: [16, 16, 16]
        model_channels: 320
        num_res_blocks: 2
        learnable_content: True
        attention_resolutions: [ 1, 2 ]
        channel_mult: [ 1, 2 ]
        num_head_channels: 64
        use_checkpoint: True
        legacy: False
        learnvar: True

    unet_config:
      target: ldm_autoencoder.ldm_autoencoder_v1.AEUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_key: "tar_frames" # current video frame
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    wrap: False
    batch_size: 16
    num_workers: 8
    train:
      target: data.custom.VideoFolderDataset_AEwT
      params:
        size: 256
        flip_p: 0.5
        num_frames: 2
        sort_index: True
        content_frame_idx:
          - 0
          - 5
          - 10
          - 15
        full_video_length: 16
        fix_prompt: "time-lapse video of sky"
        root: datasets/SkyTimelapse/sky_timelapse/reorganized_frames/trainval/FPS32
    validation:
      target: data.custom.VideoFolderDataset_AEwT
      params:
        size: 256
        num_frames: 2
        sort_index: True
        max_data_num: 2048
        allow_flip: False
        allow_point: False
        content_frame_idx:
          - 0
          - 5
          - 10
          - 15
        full_video_length: 16
        fix_prompt: "time-lapse video of sky"
        root: datasets/SkyTimelapse/sky_timelapse/reorganized_frames/trainval/FPS32

lightning:
  trainer:
    check_val_every_n_epoch: 20
    ckpt_load_strict: False
    ignore_keys:
      - discriminator
    accelerator: 'gpu'
    devices: 8
    log_gpu_memory: all
    max_epochs: 1000
    precision: 16
    auto_select_gpus: False
    strategy:
      target: strategies.DDPStrategy
      params:
        find_unused_parameters: True
    log_every_n_steps: 2
    logger: True
    default_root_dir: "experiments/"
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_imgs: True
  modelcheckpoint:
    target: lightning.pytorch.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 200
      save_top_k: 10
  logger:
    wandb:
      target: lightning.pytorch.loggers.WandbLogger
      params:
          project: control
          group: sky
