model:
  base_learning_rate: 1e-4
  target: ldm_generator.ldm_generator_v1.Generator_LDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: 8
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    learn_logvar: False
    videocontent_key: "full_frame"

    vc_size: 8
    vc_channels: 64
    latent_size: 32
    latent_channels: 4

    diffusion_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_fp16: True
        image_size: 8 # unused
        in_channels: 64
        out_channels: 64
        model_channels: 320 #768
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_key: "tar_frames" # current video frames
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: models/autoencoderkl.pth
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_key: "txt"
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

    stable_ae_config:
      target: ldm_generator.wrapper.StableAutoencoder
      params:
        linear_start: 0.00085
        linear_end: 0.0120
        log_every_t: 200
        timesteps: 1000
        image_size: 32
        channels: 4
        conditioning_key: crossattn
        monitor: val/loss_simple_ema
        use_ema: False
        learn_logvar: False
        enc_cfg:
          target: cldm.ldmae_v6.VideoContentEnc
          params:
            dims: 3
            image_size: 32
            in_channels: 4
            out_channels: 64
            model_channels: 320
            num_res_blocks: 1
            learnable_content: True
            attention_resolutions: [ 1, 2 ]
            channel_mult: [ 1, 2, 4 ]
            num_head_channels: 64
            use_checkpoint: True
            legacy: False
        diffusion_config:
          target: cldm.ldmae_v6.AEUnetModel
          params:
            image_size: 32 # unused
            in_channels: 4
            out_channels: 4
            model_channels: 320
            attention_resolutions: [ 4, 2, 1 ]
            num_res_blocks: 2
            channel_mult: [ 1, 2, 4, 4 ]
            num_heads: 8
            use_spatial_transformer: True
            transformer_depth: 1
            context_dim: 768
            use_checkpoint: True
            legacy: False
        ckpt_path: experiments/2023-03-10T22-27-24_ldm_ae_v6-1/checkpoints/epoch=0256-step=061166.ckpt

data:
  target: main.DataModuleFromConfig
  params:
    wrap: False
#    batch_size: 2 # For debug
    batch_size: 32
    num_workers: 4
    train:
      target: cldm.data.custom.VideoFolderDataset_AEwT
      params:
        size: 256
        flip_p: 0.5
        num_frames: 1
        allow_point: False # TODO
#        max_data_num: 96 # For debug
        content_frame_idx:
          - 0
          - 5
          - 10
          - 15
        full_video_length: 16
        root: datasets/UCF-101/frames_fps20
    validation:
      target: cldm.data.custom.VideoFolderDataset_AEwT
      params:
        size: 256
        num_frames: 1
#        max_data_num: 96 # for debug
        allow_flip: False
        allow_point: False
        content_frame_idx:
          - 0
          - 5
          - 10
          - 15
        full_video_length: 16
        root: datasets/UCF-101/preprocessed/ucf101_test2048_wclasses

lightning:
  trainer:
    ckpt_load_strict: False
    accelerator: 'gpu'
    devices: 4
    log_gpu_memory: all
    max_epochs: 500
    precision: 16
    auto_select_gpus: False
    strategy:
      target: strategies.DDPStrategy
      params:
        find_unused_parameters: True

    log_every_n_steps: 2
    logger: True
    default_root_dir: "experiments/"

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_imgs: False

  logger:
    wandb:
      target: lightning.pytorch.loggers.WandbLogger
      params:
          project: control
          group: ucf101
          name: nowname
          save_dir: "experiments/"
          offline: opt.debug
          id: nowname
