model:
  base_learning_rate: 1e-4
  target: ldm_autoencoder.ldm_ae_base_v3.AutoEncLDM
  params:
    kl_loss_weight: ~
    optimize_params_key: ~
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    cond_stage_key: txt
    full_index_key: full_index
    frame_index_key: frame_index
    preframe_index_key: preframe_index
    videocontent_key: key_frame
    first_stage_key: tar_frames # current video frame
    preframe_key: pre_frames
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    learn_logvar: False
    validation_log_start_epoch: 0
    validation_log_every_epochs: 1
    ddim_sampler: "ddim_v2"

    allow_gan: False
    gan_config: ~

    videoenc_config:
      target: ldm_autoencoder.ldm_ae.VideoContentEnc
      params:
        dims: 3
        image_size: 32
        in_channels: 4
        out_channels: 16
        model_channels: 320
        num_res_blocks: 2
        learnable_content: True
        attention_resolutions: [ 1, 2 ]
        channel_mult: [ 1, 2 ]
        num_head_channels: 64
        use_checkpoint: True
        legacy: False

    unet_config:
      target: ldm_autoencoder.ldm_ae.AEUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    cond_stage_config: '__is_unconditional__'
    first_stage_config:
      target: ldm_autoencoder.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    wrap: False
    batch_size: 20
    num_workers: 8 # batch size // 2
    train:
      target: data.VideoFolderDataset.VideoFolderDataset
#      target: data.VideoItemDataset.VideoItemDataset
      params:
        size: 256
        flip_p: 0.5
        num_frames: 2
        sort_index: True
        full_video_length: 16
        fix_prompt: "placeholder"
        content_frame_idx: [0, 2, 4, 6, 8, 10, 12, 14]
        root: datasets/SkyTimelapse/sky_timelapse/reorganized_frames/trainval2/FPS32
    validation:
      target: data.VideoFolderDataset.VideoFolderDataset
#      target: data.VideoItemDataset.VideoItemDataset
      params:
        size: 256
        num_frames: 2
        sort_index: True
        max_data_num: 2048
        allow_flip: False
        full_video_length: 16
        fix_prompt: "placeholder"
        content_frame_idx: [0, 2, 4, 6, 8, 10, 12, 14]
        root: datasets/SkyTimelapse/sky_timelapse/reorganized_frames/trainval2/FPS32

lightning:
  trainer:
    num_nodes: 1
#    ignore_keys:
#      - discriminator
    devices: [0,1,2,3,4,5,6,7]
    check_val_every_n_epoch: 20
    ckpt_load_strict: False
    accelerator: 'gpu'
    log_gpu_memory: all
    max_epochs: 5000
    precision: 16
    auto_select_gpus: False
    strategy:
      target: strategies.DDPStrategy
      params:
        find_unused_parameters: True
    log_every_n_steps: 2
    logger: True
    default_root_dir: "experiments/"
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_imgs: True
  modelcheckpoint:
    target: lightning.pytorch.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 200
      save_top_k: 2
  logger:
    wandb:
      target: lightning.pytorch.loggers.WandbLogger
      params:
          project: glober
          group: skytimelapse
