model:
  base_learning_rate: 1e-5
  target: cldm.cldm.ControlLDM
  params:
    sd_locked: True
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    cond_stage_key: "txt"
    control_key: "src_frame" # previous video frames
    first_stage_key: "tar_frame" # current video frame
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False
    learn_logvar: False

    control_stage_config:
      target: cldm.cldm.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    unet_config:
      target: cldm.cldm.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    wrap: False
    batch_size: 8
    # num_workwers should be 2 * batch_size, and total num less than 1024
    # e.g. if use 8 devices, no more than 128
    num_workers: 4
    train:
      target: cldm.data.custom.CustomDataset_1to1
      params:
        size: 256
        flip_p: 0.5
        max_data_num: 160
        root: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20
    validation:
      target: cldm.data.custom.CustomDataset_1to1
      params:
        size: 256
        flip_p: 0.5
#        max_data_num: 2048
        max_data_num: 160
        root: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20

lightning:
  trainer:
    ckpt_load_strict: False
    accelerator: 'gpu'
    devices: 4
    log_gpu_memory: all
    max_epochs: 500
    precision: 16
    auto_select_gpus: False
    strategy:
      target: strategies.DDPStrategy
      params:
        find_unused_parameters: True
#    strategy:
#      target: strategies.ColossalAIStrategy
#      params:
#        use_chunk: True
#        enable_distributed_storage: True
#        placement_policy: cuda
#        force_outputs_fp32: true
#        min_chunk_size: 64

    log_every_n_steps: 2
    logger: True
    default_root_dir: "experiments/"

  logger:
    wandb:
      target: lightning.pytorch.loggers.WandbLogger
      params:
          project: control
          group: ucf101
          name: nowname
          save_dir: "experiments/"
          offline: opt.debug
          id: nowname
